2024-03-02 20:11:49,362 : INFO : Start of Training
2024-03-02 20:11:49,362 : INFO : Run_id:<bound method Config.run_id of <apps.core.config.Config object at 0x7f1d5d688d00>>
2024-03-02 20:11:49,363 : INFO : Start of reading dataset...
2024-03-02 20:11:53,944 : INFO : End of reading dataset...
2024-03-02 20:11:53,945 : INFO : Start of splitting features and label ...
2024-03-02 20:11:53,946 : INFO : End of splitting features and label ...
2024-03-02 20:11:53,947 : INFO : Saving to database
2024-03-02 20:13:30,048 : INFO : Opened used_cars database successfully
2024-03-02 20:13:50,230 : INFO : Start of creating table...
2024-03-02 20:13:57,439 : INFO : Opened used_cars database successfully
2024-03-02 20:16:32,368 : ERROR : Exception raised while creating table: 'Index' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 48, in create_table
    for key, type_of_column in self.column_names.items():
AttributeError: 'Index' object has no attribute 'items'
2024-03-02 20:16:32,371 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/training/train.py", line 51, in training_model
    pg_db.create_table(self.training_db, "uc_training_data")
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 60, in create_table
    raise e
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 48, in create_table
    for key, type_of_column in self.column_names.items():
AttributeError: 'Index' object has no attribute 'items'
